platform :ios, "8.0"

target "WangZuan" do

pod 'SDWebImage'
pod 'AFNetworking'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'Masonry'
pod 'MJRefresh'
pod 'IQKeyboardManager'#, '~> 4.0.8'
pod 'YTKNetwork'
pod 'YYText', '~> 1.0.7'
pod 'MCUIColorUtils'
pod 'BANetManager'#, '~> 2.2.2'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'AvoidCrash'#, '~> 2.3.0-beta'    #防止闪退
pod 'WRNavigationBar'
pod 'JPush'
pod 'BRPickerView'
pod 'SDCycleScrollView'
end
